### PR TITLE
Fix indentation for email configuration

### PR DESCRIPTION
**Pull request by dguo**

### CODE REVIEW

**Comment by dguo** [comment]
On second thought, I'm not sure if the email example is incorrect or the Slack example.

**Comment by manishas** [comment]
Thanks for the PR! We would love to send you some stickers and swag as a thank you.... please send your mailing address to abhijit@shippable.com so we can send it.

**Comment by abhijitkini** [comment]
@dguo your stickers are on the way. Thanks again!

**Comment by dguo** [comment]
Thank you! That's a nice surprise.

**Pull request merged**
