### PR TITLE
Move Get Started CTA below right side nav + Fix Docker Datacenter tutorial missing images

### PR DESCRIPTION
**Pull request by xdothackerx**
image

### CODE REVIEW

**Comment by avinci** [comment]
I think we need 5em top section separator horizontally.

**Comment by avinci** [comment]
menus and content is getting to tight up. second, there needs to be 5em separator between right size menu and the CTA.

**Comment by xdothackerx** [comment]
image

**Comment by xdothackerx** [comment]
Also, 
Closes https://github.com/Shippable/pm/issues/6670

**Comment by avinci** [comment]
this is missing the 5em margin from top

**Comment by xdothackerx** [comment]
image
Added!

**Pull request merged**
